#!/bin/sh
#
NAME="wifistats-sample"

case `uname` in
  Darwin)	exec /cslinux/bin/$NAME-osx $*
		;;
  Linux)	exec /cslinux/bin/$NAME-linux $*
		;;
  *)		echo "$0: not supported on this architecture"
		exit 1
		;;
esac
